numAX=8;
numAY=16;
numYY = 16;
ispractice=1;
praccuestimTable = GenAXCPTtable(numAX,numAY,numYY,ispractice);
numAX=32;
numAY=64;
numYY = 64;
ispractice=0;
cuestimTable = GenAXCPTtable(numAX,numAY,numYY,ispractice);
outtable = [praccuestimTable; cuestimTable];
writetable(outtable,'.\data\AXCPT.csv');
